version: "3.8"

services:
  crm_kts_image:
    platform: linux/amd64
    build: .
    command: gunicorn ktscrm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL=postgres://django_ktscrm:c7VL09DcUnXGKVysq0fV!$@127.0.0.1:5432/crm-kts

