# Generated by Django 4.2.15 on 2025-01-30 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panicbutton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание объекта')),
                ('object_type', models.CharField(blank=True, max_length=255, verbose_name='Тип объекта')),
                ('route_info', models.TextField(blank=True, verbose_name='Текстовое обозначение маршрута')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('contract', models.CharField(blank=True, max_length=50, verbose_name='Договор')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
