# Generated by Django 4.2.15 on 2025-02-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0002_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='API-ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panicbutton.clientprofile', verbose_name='Клиент')),
            ],
        ),
    ]
