# Generated by Django 4.2.15 on 2025-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='last_alarm_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя тревога'),
        ),
    ]
