# Generated by Django 4.2.15 on 2025-02-26 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panicbutton', '0004_clientprofile_last_alarm_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='client',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='is_active',
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=40, unique=True, verbose_name='API-ключ'),
        ),
    ]
