# Generated by Django 4.2.15 on 2025-02-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0005_remove_apikey_client_remove_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='API-ключ'),
        ),
    ]
