# Generated by Django 4.2.15 on 2025-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0006_alter_apikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время прибытия'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='ekipaz_panic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Экипаж'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='intercom_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код домофона'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='technical_spec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Техник'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
