# Generated by Django 4.2.15 on 2025-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0007_clientprofile_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='floor_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажей'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='name_client',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя клиента'),
        ),
    ]
