# Generated by Django 4.2.15 on 2025-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panicbutton', '0008_clientprofile_floor_total_clientprofile_name_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('pending', 'Ожидает обработки'), ('in_progress', 'В работе'), ('resolved', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
