# Generated by Django 4.2.3 on 2024-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepteddate', models.DateTimeField(blank=True, null=True)),
                ('arrivaldate', models.DateTimeField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=256, null=True)),
                ('closed', models.BooleanField()),
                ('closeddate', models.DateTimeField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('report', models.CharField(blank=True, max_length=1024, null=True)),
                ('zones', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmeddate', models.DateTimeField(blank=True, null=True)),
                ('technicianreport', models.CharField(blank=True, max_length=1024, null=True)),
                ('clazz', models.CharField(blank=True, max_length=32, null=True)),
                ('customcause', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alarms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=31)),
                ('clazz', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField()),
                ('fridayenabled', models.BooleanField()),
                ('fridayend', models.TimeField(blank=True, null=True)),
                ('fridaystart', models.TimeField(blank=True, null=True)),
                ('mondayenabled', models.BooleanField()),
                ('mondayend', models.TimeField(blank=True, null=True)),
                ('mondaystart', models.TimeField(blank=True, null=True)),
                ('saturdayenabled', models.BooleanField()),
                ('saturdayend', models.TimeField(blank=True, null=True)),
                ('saturdaystart', models.TimeField(blank=True, null=True)),
                ('sundayenabled', models.BooleanField()),
                ('sundayend', models.TimeField(blank=True, null=True)),
                ('sundaystart', models.TimeField(blank=True, null=True)),
                ('thursdayenabled', models.BooleanField()),
                ('thursdayend', models.TimeField(blank=True, null=True)),
                ('thursdaystart', models.TimeField(blank=True, null=True)),
                ('tuesdayenabled', models.BooleanField()),
                ('tuesdayend', models.TimeField(blank=True, null=True)),
                ('tuesdaystart', models.TimeField(blank=True, null=True)),
                ('wednesdayenabled', models.BooleanField()),
                ('wednesdayend', models.TimeField(blank=True, null=True)),
                ('wednesdaystart', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alarm_schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'authorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=31)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('section', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'causes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ext', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('uploadtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuardedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('addressbycoords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путо в базе')),
                ('addressintersection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пересечение улиц')),
                ('arrivingtime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время прибытия')),
                ('connectionfrom', models.DateTimeField(blank=True, null=True, verbose_name='Дата подключения')),
                ('contract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Не используется')),
                ('contractnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер договора')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления на сайт')),
                ('crew', models.CharField(blank=True, max_length=255, null=True, verbose_name='Экипаж')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Описание объекта')),
                ('drivingdirections', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Маршрут следования')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж')),
                ('floortotal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этажей всего:')),
                ('forcecode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Не используется')),
                ('guardtime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Не исползьзуется')),
                ('haskeys', models.CharField(blank=True, max_length=255, null=True, verbose_name='Не исползьзуется')),
                ('importance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Степень важности объекта')),
                ('intercomcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код домофона')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Этаж')),
                ('legalentity', models.BooleanField(verbose_name='Юрик')),
                ('literal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Литер')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер объекта')),
                ('objectenterways', models.CharField(blank=True, max_length=255, null=True, verbose_name='Не используется')),
                ('reactionfrom', models.DateTimeField(blank=True, null=True, verbose_name='Не исользуется')),
                ('schemaauthor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Схему составил')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип объекта')),
                ('technician', models.CharField(blank=True, max_length=255, null=True, verbose_name='Участок техника')),
                ('pdfgenerated', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guarded_objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuardedZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('resources', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'guarded_zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LetterCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'letter_counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isgroup', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('lastlogindate', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('sessionttl', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.CharField(max_length=36)),
                ('session_id', models.CharField(max_length=36)),
                ('creation_time', models.BigIntegerField()),
                ('last_access_time', models.BigIntegerField()),
                ('max_inactive_interval', models.IntegerField()),
                ('expiry_time', models.BigIntegerField()),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersSessionsAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_primary_id', models.CharField(max_length=36)),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_bytes', models.BinaryField(max_length='max')),
            ],
            options={
                'db_table': 'users_sessions_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=255)),
                ('json', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
    ]
