# Generated by Django 4.2.3 on 2024-05-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ekipazh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipazh_name', models.CharField(max_length=255, null=True, verbose_name='Название экипажа')),
            ],
            options={
                'verbose_name': 'Экипажи',
                'verbose_name_plural': 'Экипажи',
            },
        ),
        migrations.CreateModel(
            name='partners_rekvizity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehnic_srv_cost_ur', models.IntegerField(blank=True, null=True, verbose_name='Стоимость тех обслуживания Юр.лица')),
                ('tehnic_srv_cost_fiz', models.IntegerField(blank=True, null=True, verbose_name='Стоимость тех обслуживания Физ.лица')),
                ('pozharka_fiz', models.IntegerField(blank=True, null=True, verbose_name='Пожарная сигналзиция Физ.лица')),
                ('pozharka_ur', models.IntegerField(blank=True, null=True, verbose_name='Пожарная сигналзиция Юр.лица')),
                ('nabludenie_fiz', models.IntegerField(blank=True, null=True, verbose_name='Наблюдение Физ.лица')),
                ('nabludenie_ur', models.IntegerField(blank=True, null=True, verbose_name='Наблюдение Юр.лица')),
                ('arenda_fiz', models.IntegerField(blank=True, null=True, verbose_name='Аренда GSM Физ.лица')),
                ('arenda_ur', models.IntegerField(blank=True, null=True, verbose_name='Аренда GSM Юр.лица')),
                ('telemetria', models.IntegerField(blank=True, null=True, verbose_name='Телеметрия')),
                ('sms', models.IntegerField(blank=True, null=True, verbose_name='SMS')),
                ('polnoe_name', models.CharField(max_length=255, null=True, verbose_name='Полное название компании')),
                ('adres_company', models.CharField(max_length=255, null=True, verbose_name='Адрес компании')),
                ('bin', models.CharField(max_length=255, null=True, verbose_name='БИН')),
                ('iban', models.CharField(max_length=255, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=255, null=True, verbose_name='BIC')),
                ('bank', models.CharField(max_length=255, null=True, verbose_name='BANK')),
                ('telephone_ofiice', models.CharField(max_length=255, null=True, verbose_name='Телефон офиса')),
                ('telephone_buh', models.CharField(max_length=255, null=True, verbose_name='Телефон бухгалтерии')),
                ('vid_too', models.CharField(max_length=255, null=True, verbose_name='Вид ТОО')),
                ('doljnost', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('ucheriditel_name_polnoe', models.CharField(max_length=255, null=True, verbose_name='ФИО директора')),
                ('ucheriditel_name_sokr', models.CharField(max_length=255, null=True, verbose_name='ФИО директора сокращенно')),
            ],
            options={
                'verbose_name': 'Реквизиты партнеров',
                'verbose_name_plural': 'Реквизиты партнеров',
            },
        ),
        migrations.CreateModel(
            name='rekvizity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polnoe_name', models.CharField(max_length=255, null=True, verbose_name='Полное название компании')),
                ('adres_company', models.CharField(max_length=255, null=True, verbose_name='Адрес компании')),
                ('bin', models.CharField(max_length=255, null=True, verbose_name='БИН')),
                ('iban', models.CharField(max_length=255, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=255, null=True, verbose_name='BIC')),
                ('bank', models.CharField(max_length=255, null=True, verbose_name='BANK')),
                ('telephone_ofiice', models.CharField(max_length=255, null=True, verbose_name='Телефон офиса')),
                ('telephone_buh', models.CharField(max_length=255, null=True, verbose_name='Телефон бухгалтерии')),
                ('vid_too', models.CharField(max_length=255, null=True, verbose_name='Вид ТОО')),
                ('doljnost', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('ucheriditel_name_polnoe', models.CharField(max_length=255, null=True, verbose_name='ФИО директора')),
                ('ucheriditel_name_sokr', models.CharField(max_length=255, null=True, verbose_name='ФИО директора сокращенно')),
            ],
            options={
                'verbose_name': 'Реквизиты компаний',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
        migrations.CreateModel(
            name='vid_sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sign', models.CharField(max_length=255, null=True, verbose_name='Вид сигнализации')),
                ('name_sign_polnoe', models.CharField(max_length=255, null=True, verbose_name='Полное имя сигнализации')),
            ],
            options={
                'verbose_name': 'Вид сигнализации',
                'verbose_name_plural': 'Вид сигнализации',
            },
        ),
        migrations.CreateModel(
            name='partners_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер объекта')),
                ('gsm_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер GSM')),
                ('name_object', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование клиента')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('type_object', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип объекта')),
                ('hours_mounth', models.IntegerField(blank=True, null=True, verbose_name='Часы в месяц')),
                ('date_podkluchenia', models.DateField(blank=True, null=True, verbose_name='Дата подключения')),
                ('tariff_per_mounth', models.IntegerField(blank=True, null=True, verbose_name='Тариф за мониторинг и реагирвание в месяц')),
                ('tehnical_services', models.BooleanField(default=False, null=True, verbose_name='Тех.обслуживание')),
                ('rent_gsm', models.BooleanField(default=False, null=True, verbose_name='Аренда GSM')),
                ('fire_alarm', models.BooleanField(default=False, null=True, verbose_name='Пожарная сигналзиция')),
                ('telemetria', models.BooleanField(default=False, null=True, verbose_name='Телеметрия')),
                ('nabludenie', models.BooleanField(default=False, null=True, verbose_name='Наблюдение')),
                ('sms_uvedomlenie', models.BooleanField(default=False, null=True, verbose_name='SMS уведомление')),
                ('kolvo_day', models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней')),
                ('primechanie', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('urik', models.BooleanField(default=False, null=True, verbose_name='Юридическое лицо')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogovornoy.partners_rekvizity', verbose_name='Партнеры')),
                ('ekipazh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogovornoy.ekipazh', verbose_name='Экипаж')),
                ('vid_sign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogovornoy.vid_sign', verbose_name='Вид сигнализации')),
            ],
            options={
                'verbose_name': 'Объекты партнеров',
                'verbose_name_plural': 'Объекты партнеров',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='kts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udv_number', models.CharField(max_length=255, null=True, verbose_name='Номер УДВ')),
                ('date_udv', models.CharField(max_length=255, null=True, verbose_name='Дата и Кем выдано')),
                ('dogovor_number', models.CharField(max_length=255, null=True, verbose_name='№ дог.')),
                ('data_zakluchenia', models.CharField(max_length=255, null=True, verbose_name='Дата заключения')),
                ('nalichiye_dogovora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наличие Договора')),
                ('mat_otv', models.CharField(max_length=100, null=True, verbose_name='Мат.отв')),
                ('act_ty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Акты ТУ')),
                ('time_reag', models.IntegerField(null=True, verbose_name='Время реагирования')),
                ('time_reag_nebol', models.IntegerField(null=True, verbose_name='Реагирование не более')),
                ('yslovie_dogovora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Условия договора')),
                ('klient_name', models.TextField(null=True, verbose_name='Наименование Клиента')),
                ('name_object', models.TextField(null=True, verbose_name='Наименование объекта')),
                ('adres', models.TextField(null=True, verbose_name='Адрес объекта')),
                ('iin_bin', models.CharField(max_length=255, null=True, verbose_name='ИИН/БИН')),
                ('telephone', models.TextField(null=True, verbose_name='Телефон')),
                ('urik', models.BooleanField(default=False, null=True, verbose_name='Юридическое лицо')),
                ('chasi_po_dog', models.IntegerField(null=True, verbose_name='Часы по договору')),
                ('dop_uslugi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Алсеко')),
                ('abon_plata', models.IntegerField(blank=True, null=True, verbose_name='Абон.плата')),
                ('object_number', models.IntegerField(blank=True, null=True, verbose_name='№ объекта')),
                ('peredatchik_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ передатчика/GSM')),
                ('stoimost_rpo', models.IntegerField(null=True, verbose_name='Стоимость РПО')),
                ('date_podkluchenia', models.DateField(blank=True, null=True, verbose_name='Дата подключения')),
                ('date_otklulchenia', models.DateField(blank=True, null=True, verbose_name='Дата отключения')),
                ('gruppa_reagirovania', models.CharField(blank=True, max_length=255, null=True, verbose_name='Группа реагирования')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронный адрес')),
                ('vid_rpo', models.TextField(blank=True, null=True, verbose_name='Вид РПО')),
                ('primechanie', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('agentskie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Агентские')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото УДВ')),
                ('prochee', models.TextField(blank=True, null=True, verbose_name='Прочее')),
                ('exclude_from_report', models.BooleanField(default=False, verbose_name='Не учитывать в отчете')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogovornoy.rekvizity', verbose_name='Компания')),
                ('vid_sign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogovornoy.vid_sign', verbose_name='Вид сигнализации')),
            ],
            options={
                'verbose_name': 'База договоров',
                'verbose_name_plural': 'База договоров',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название доп.услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='Дата подключения')),
                ('date_unsubscribe', models.DateField(blank=True, null=True, verbose_name='Дата отключения')),
                ('kts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='dogovornoy.kts')),
            ],
            options={
                'verbose_name': 'Доп.Услуги',
                'verbose_name_plural': 'Доп.Услуги',
                'ordering': ['-pk'],
            },
        ),
    ]
