# Generated by Django 4.2.3 on 2024-05-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners_object',
            name='date_otkluchenia',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отключения'),
        ),
    ]
