# Generated by Django 4.2.15 on 2024-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0002_returnreason_skaldgsm2_return_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='returnreason',
            options={'verbose_name': 'Причины возврата GSM', 'verbose_name_plural': 'Причины возврата GSM'},
        ),
    ]
