# Generated by Django 4.2.3 on 2024-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0003_partners_object_sms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners_rekvizity',
            name='nabludenie_dom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Наблюдение Физ.лица дом'),
        ),
        migrations.AddField(
            model_name='partners_rekvizity',
            name='nabludenie_kv',
            field=models.IntegerField(blank=True, null=True, verbose_name='Наблюдение Физ.лица квартира'),
        ),
    ]
