# Generated by Django 4.2.15 on 2024-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0004_rekvizity_img_pechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltask',
            name='previous_workstation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущее значение WORKSTATION'),
        ),
    ]
