# Generated by Django 4.2.3 on 2024-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0004_partners_rekvizity_nabludenie_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners_rekvizity',
            name='sms_ur',
            field=models.IntegerField(blank=True, null=True, verbose_name='SMS Юрики'),
        ),
    ]
