# Generated by Django 4.2.15 on 2024-12-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0005_technicaltask_previous_workstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='technicaltask',
            name='result',
            field=models.TextField(blank=True, verbose_name='Результат'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Сайт'), ('call', 'Звонок в офис')], max_length=100, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogovornoy.kanbanstatus', verbose_name='Статус')),
            ],
        ),
    ]
