# Generated by Django 4.2.3 on 2024-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0005_partners_rekvizity_sms_ur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners_object',
            name='tariff_per_mounth',
            field=models.FloatField(blank=True, null=True, verbose_name='Тариф за мониторинг и реагирвание в месяц'),
        ),
    ]
