# Generated by Django 4.2.15 on 2025-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0006_kanbanstatus_alter_technicaltask_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('website', 'Сайт'), ('call', 'Звонок в офис'), ('wuzzup', 'WhatsApp Wuzzup')], max_length=100, verbose_name='Источник'),
        ),
    ]
