# Generated by Django 4.2.3 on 2024-07-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0010_alter_task_assigned_to_alter_task_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
