# Generated by Django 4.2.15 on 2024-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0013_alter_technicaltask_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltask',
            name='ekcbase_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
