# Generated by Django 4.2.15 on 2024-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovornoy', '0015_kts_bank_kts_bik_kts_dolznost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners_object',
            name='prochee',
            field=models.TextField(blank=True, null=True, verbose_name='Прочее'),
        ),
    ]
