# Generated by Django 4.2.15 on 2024-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGsm2Moduls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_id', models.IntegerField(db_column='Модуль')),
                ('module_type', models.CharField(db_column='Тип', max_length=255)),
                ('date', models.DateField(db_column='Дата')),
                ('quality', models.IntegerField(db_column='Качество')),
                ('internet', models.CharField(db_column='Интернет', max_length=255)),
                ('cellular', models.CharField(db_column='Сот.', max_length=255)),
                ('sms_count', models.IntegerField(db_column='Кол. SMS')),
                ('sn', models.CharField(db_column='SN', max_length=255)),
                ('org_id', models.IntegerField(db_column='ORGID')),
                ('color', models.IntegerField(db_column='COLOR')),
            ],
            options={
                'db_table': 'v_GSM2MODULS',
                'managed': False,
            },
        ),
    ]
